name: Build Sample App for CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "**.md"
  pull_request:
    branches: [ "main" ]

env:
  BUILD_CONFIGURATION: Release

jobs:
  build-sample-ci:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
  
    - name: Setup MSBuild path
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: 'latest'

    - name: Build Maui Sample
      run: dotnet build samples\Plugin.Maui.OCR.Sample.sln -c ${{env.BUILD_CONFIGURATION}}

    - name: Restore NuGet packages
      run: msbuild /t:Restore src\Plugin.Xamarin.OCR.Sample.sln -maxcpucount
       
    - name: Build Xamarin Sample
      run: msbuild /m /t:Build samples\Plugin.Xamarin.OCR.Sample.sln /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:RestorePackages=false -maxcpucount
    
