name: Build Sample App for CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "**.md"
  pull_request:
    branches: [ "main" ]

jobs:
  build-sample-ci:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build Maui Sample
      run: dotnet build samples\Plugin.Maui.OCR.Sample.sln -c Release
    - name: Build Xamarin Sample
      run: dotnet build samples\Plugin.Xamarin.OCR.Sample.sln -c Release
    
