name: Build Sample App for CI

on:
  push:
    branches: [ $default-branch ]
    paths-ignore:
      - "**.md"
  pull_request:
    branches: [ $default-branch ]

env:
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build-sample-ci:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
  
    - name: Setup MSBuild path
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: 'latest'

    - name: Build Maui Sample
      run: dotnet build samples\Plugin.Maui.OCR.Sample.sln -c ${{env.BUILD_CONFIGURATION}}

    - name: Restore NuGet packages
      run: msbuild /t:Restore src\Plugin.Xamarin.OCR.Sample.sln

    - name: Build Xamarin Sample
      run: msbuild /m /t:Build samples\Plugin.Xamarin.OCR.Sample.sln /p:Configuration=${{env.BUILD_CONFIGURATION}}
    
