name: Build Sample App for CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "**.md"
  pull_request:
    branches: [ "main" ]

jobs:
  build-sample-ci:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup MSBuild path
      uses: microsoft/setup-msbuild@v1.1
    - name: Build Maui Sample
      run: dotnet build samples\Plugin.Maui.OCR.Sample.sln -c Release
    - name: Restore NuGet packages
      run: msbuild /t:Restore src\Plugin.Xamarin.OCR.Sample.sln
    - name: Build Xamarin Sample
      run: msbuild samples\Plugin.Xamarin.OCR.Sample.sln /p:Configuration=Release /m
    
