name: Build for CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "**.md"
  pull_request:
    branches: [ "main" ]

jobs:
  build-plugin-ci:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build Maui
      run: dotnet build src\Plugin.Maui.OCR.sln -c Release
    - name: Build Xamarin
      run: dotnet build src\Plugin.Xamarin.OCR.sln -c Release
