name: Build for CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "**.md"
  pull_request:
    branches: [ "main" ]

env:
  BUILD_CONFIGURATION: Release

jobs:
  build-plugin-ci:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSBuild path
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: 'latest'

    - name: Build Maui
      run: dotnet build src\Plugin.Maui.OCR.sln -c ${{env.BUILD_CONFIGURATION}}

    - name: Restore NuGet packages
      run: msbuild /t:Restore src\Plugin.Xamarin.OCR.sln

    - name: Build Xamarin
      run: msbuild /m /t:Build src\Plugin.Xamarin.OCR.sln /p:Configuration=${{env.BUILD_CONFIGURATION}}
